In [19]:

pip install nba_api

Collecting nba_api
  Downloading nba_api-1.11.4-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=2.1.0 in ./.venv/lib/python3.14/site-packages (from nba_api) (2.4.4)
Requirement already satisfied: pandas>=2.2.0 in ./.venv/lib/python3.14/site-packages (from nba_api) (3.0.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in ./.venv/lib/python3.14/site-packages (from nba_api) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.14/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
Downloading nba_api-1.11.4-py3-none-any.whl (322 kB)
Installing collected packages: nba_api
Successfully installed nba_api-1.11.4

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import json
import time
from nba_api.stats.endpoints import leaguegamelog
from nba_api.stats.library.parameters import SeasonType

def get_nba_games(start_year, end_year):
    all_games = []
    #filter for more than 10 games played
    
    for year in range(start_year, end_year):
        season_str = f"{year}-{str(year+1)[2:]}"
        print(f"Fetching {season_str}...")
        
        try:
            log = leaguegamelog.LeagueGameLog(season=season_str, season_type_all_star=SeasonType.regular)
            

            data_dict = log.get_dict()['resultSets'][0]
            headers = data_dict['headers']
            rows = data_dict['rowSet']
            

            for row in rows:
                game_entry = dict(zip(headers, row))
                all_games.append(game_entry)
                
            time.sleep(1)
        except Exception as e:
            print(f"Error on {season_str}: {e}")


    with open('nba_games_2004_2026.json', 'w') as f:
        json.dump(all_games, f, indent=4)

get_nba_games(2004, 2026)

Fetching 2004-05...
Fetching 2005-06...
Fetching 2006-07...
Fetching 2007-08...
Fetching 2008-09...
Fetching 2009-10...
Fetching 2010-11...
Fetching 2011-12...
Fetching 2012-13...
Fetching 2013-14...
Fetching 2014-15...
Fetching 2015-16...
Fetching 2016-17...
Fetching 2017-18...
Fetching 2018-19...
Fetching 2019-20...
Fetching 2020-21...
Fetching 2021-22...
Fetching 2022-23...
Fetching 2023-24...
Fetching 2024-25...
Fetching 2025-26...

In [ ]:
import json
import time
from nba_api.stats.endpoints import playergamelogs
from nba_api.stats.library.parameters import SeasonType

def get_player_stats(start_year, end_year):
    all_player_stats = []
    
    for year in range(start_year, end_year):
        season_str = f"{year}-{str(year+1)[2:]}"
        print(f"Fetching player stats for {season_str}...")
        
        try:
    
            log = playergamelogs.PlayerGameLogs(
                season_nullable=season_str,
                season_type_nullable=SeasonType.regular
            )
            
            data_dict = log.get_dict()['resultSets'][0]
            headers = data_dict['headers']
            rows = data_dict['rowSet']
            

            for row in rows:
                stat_entry = dict(zip(headers, row))
                #get rid of rank and fantasy
                clean_entry={k:v for k,v in stat_entry.items() if"_RANK" not in k and "FANTASY" not in k}
                clean_entry["GAME_DATE"] = clean_entry["GAME_DATE"].split("T")[0]
                all_player_stats.append(clean_entry)
                

            time.sleep(1.5)
            
        except Exception as e:
            print(f"Error fetching {season_str}: {e}")

 
    with open('nba_player_stats_2004_2026.json', 'w') as f:
        json.dump(all_player_stats, f, indent=4)
    
    print(f"Saved {len(all_player_stats)} player stat lines to JSON.")


get_player_stats(2004, 2026)

Fetching player stats for 2004-05...
Fetching player stats for 2005-06...
Fetching player stats for 2006-07...
Fetching player stats for 2007-08...
Fetching player stats for 2008-09...
Fetching player stats for 2009-10...
Fetching player stats for 2010-11...
Fetching player stats for 2011-12...
Fetching player stats for 2012-13...
Fetching player stats for 2013-14...
Fetching player stats for 2014-15...
Fetching player stats for 2015-16...
Fetching player stats for 2016-17...
Fetching player stats for 2017-18...
Fetching player stats for 2018-19...
Fetching player stats for 2019-20...
Fetching player stats for 2020-21...
Fetching player stats for 2021-22...
Fetching player stats for 2022-23...
Fetching player stats for 2023-24...
Fetching player stats for 2024-25...
Fetching player stats for 2025-26...
Saved 553716 player stat lines to JSON.

In [5]:
import pandas as pd
#games=pd.read_csv("csv/games.csv")
player_statistics=pd.read_csv("/csv/PlayerStatistics.csv")
#team_histories=pd.read_csv("csv/TeamHistories.csv")
#team_statistics=pd.read_csv("csv/TeamStatistics.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/csv/PlayerStatistics.csv'

In [1]:
#filter to games after august 1 2004
#games_after_2004=games[games["gameDateTimeEst"]>"2004-08-01"]
player_statistics_after_2004=player_statistics[player_statistics["gameDateTimeEst"]>"2004-08-01"]
#team_statistics_after_2004=team_statistics[team_statistics["gameDateTimeEst"]>"2004-08-01"]

NameError: name 'player_statistics' is not defined

In [35]:
player_statistics_after_2004
#player_statistics_after_2004.to_json("json/player_statistics.json",orient="records",lines=True)
#team_histories.to_json("json/team_histories.json",orient="records",lines=True)

,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,opponentteamName,gameType,...,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints
0,Gary,Payton II,1627780.0,22501170,2026-04-09 22:00:00,Golden State,Warriors,Los Angeles,Lakers,Regular Season,...,0.000,2.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,12.0
1,Luke,Kennard,1628379.0,22501170,2026-04-09 22:00:00,Los Angeles,Lakers,Golden State,Warriors,Regular Season,...,0.500,1.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,20.0
2,Maxi,Kleber,1628467.0,22501170,2026-04-09 22:00:00,Los Angeles,Lakers,Golden State,Warriors,Regular Season,...,0.000,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,-10.0
3,De'Anthony,Melton,1629001.0,22501170,2026-04-09 22:00:00,Golden State,Warriors,Los Angeles,Lakers,Regular Season,...,0.000,0.0,0.0,0.0,3.0,0.0,3.0,0.0,2.0,-12.0
4,Jarred,Vanderbilt,1629020.0,22501170,2026-04-09 22:00:00,Los Angeles,Lakers,Golden State,Warriors,Regular Season,...,0.000,0.0,0.0,0.0,5.0,1.0,6.0,0.0,4.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769137,Bernard,Robinson,2774.0,10400065,2004-10-22 19:00:00,Charlotte,Bobcats,Portland,Trail Blazers,Preseason,...,0.000,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0
769138,Theo,Ratliff,689.0,10400065,2004-10-22 19:00:00,Portland,Trail Blazers,Charlotte,Bobcats,Preseason,...,0.000,2.0,2.0,1.0,5.0,3.0,8.0,2.0,3.0,0.0
769139,Damon,Stoudamire,757.0,10400065,2004-10-22 19:00:00,Portland,Trail Blazers,Charlotte,Bobcats,Preseason,...,0.111,1.0,1.0,1.0,2.0,1.0,3.0,3.0,4.0,0.0
769140,Nick,Van Exel,89.0,10400065,2004-10-22 19:00:00,Portland,Trail Blazers,Charlotte,Bobcats,Preseason,...,0.000,2.0,2.0,1.0,3.0,0.0,3.0,1.0,3.0,0.0
769141,Shareef,Abdur-Rahim,949.0,10400065,2004-10-22 19:00:00,Portland,Trail Blazers,Charlotte,Bobcats,Preseason,...,0.000,2.0,1.0,0.5,3.0,3.0,6.0,0.0,2.0,0.0

In [31]:
team_statistics_after_2004

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId
0,22501170,2026-04-09 22:00:00,Golden State,Warriors,1610612744,Los Angeles,Lakers,1610612747,1,0.0,...,2.0,8.0,22.0,54.0,18.0,3.0,0.0,37.0,43.0,NaN
1,22501170,2026-04-09 22:00:00,Los Angeles,Lakers,1610612747,Golden State,Warriors,1610612744,0,1.0,...,2.0,18.0,28.0,48.0,10.0,3.0,1.0,51.0,29.0,NaN
2,22501169,2026-04-09 20:00:00,Houston,Rockets,1610612745,Philadelphia,76ers,1610612755,1,1.0,...,7.0,14.0,22.0,52.0,18.0,5.0,1.0,51.0,29.0,NaN
3,22501169,2026-04-09 20:00:00,Philadelphia,76ers,1610612755,Houston,Rockets,1610612745,0,0.0,...,7.0,12.0,13.0,48.0,24.0,5.0,0.0,43.0,37.0,NaN
4,22501168,2026-04-09 19:30:00,Boston,Celtics,1610612738,New York,Knicks,1610612752,0,0.0,...,16.0,12.0,8.0,32.0,18.0,13.0,0.0,54.0,26.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60239,10400064,2004-10-22 19:30:00,Denver,Nuggets,1610612743,Golden State,Warriors,1610612744,0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60240,10400064,2004-10-22 19:30:00,Golden State,Warriors,1610612744,Denver,Nuggets,1610612743,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60241,10400068,2004-10-22 19:30:00,New Jersey,Nets,1610612751,Boston,Celtics,1610612738,0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60242,10400065,2004-10-22 19:00:00,Portland,Trail Blazers,1610612757,Charlotte,Bobcats,1610612766,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60243,10400065,2004-10-22 19:00:00,Charlotte,Bobcats,1610612766,Portland,Trail Blazers,1610612757,1,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
#games_after_2004=games_after_2004.drop(columns=["gameSubtype","gameLabel","gameSubLabel","seriesGameNumber"])
team_statistics_after_2004=team_statistics_after_2004.drop(columns=["pointsFastBreak","pointsFromTurnovers","pointsInThePaint","pointsSecondChance","timesTied","timeoutsRemaining","coachId"])
#games_after_2004.to_json("json/games.json",orient="records",lines=True)
team_statistics_after_2004.to_json("json/team_statistics.json",orient="records",lines=True)